version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - 6600:4000
    volumes:
      - ./:/usr/local/apps/server
    links:
      - proxy
      - memory
    depends_on:
      - proxy
      - memory
  proxy:
    image: dockage/tor-privoxy
    restart: always
  memory:
    image: redis
    restart: always
    ports:
      - 6601:6379
    volumes:
      - memory:/redis/data
volumes:
  memory:
